language: node_js
node_js:
- '6'
- '8'
- '10'
deploy:
  api_key:
    secure: LjLL7yWhJSZfS7eXrHI0GLe9prA4pkCvJONX8qe7wAdJsT2+MoqDq2Jh0zH3jldvPq/P3Fj66e8zhzvwviKkfRnotSp/1Lwj9JYi0RN8FeJ0vLhE5XWfnwfGrkxymawT139bcRqPY8rRquHWIy62SU6zRouxz0B5PVcY97J1125bJC3GZtdX2JbHbVpC9X9OkTLqbWqa9Bmup2crqJ+TFzTeYBceFS1DONpQodoTRa20crQ5yHUiGhESLbzP/0DnwSJd2I7oDMqFdyxWXIdCleNtCKANuvDf2wxTsjRwKAsXmnizrQ241prhx51LEfvny4GNAZXEYwN7VSsSiAI6wbcyV4ORgnPEqZ42aUyzH4G57VkKxGljEZqYDG+Z1w/rSpPBuolmZdSHRAOcVxn1Z/wVMGbI+raqkzs0TC1VufMP28cLkkZ64c58nKuVaofPsUi4ZiXEsUerrkEdiQv/BctPcfp0rLzZJjiDKhbr/6CEtywjZheAg8t6Q1bwvHYK2yoGh1/peXmGXIar5G0c6I8axQALRcYu/HEXs20pjCa9TCdZ+W3uCsUDzjKrRA/mpHy3HlxlVGsmjn21ChW7KQgRIXlhqSMK9vrpI5bv5AysaOLXZtA/DlmYbI/5Dz5vY+uB3/t+cs8pa6GCrxsI7vxiQCYZmGyhi+TnGPr7loY=
  email: julian@dotcore.co.il
  provider: npm
  skip_cleanup: true # prevent having to rebuild all files
  on:
    tags: true
after_script:
- npm run coveralls
